$("#cnetToolbarWrap").remove()
$("header").remove()
$("#leaderboard").remove()
$(".sidebar").hide()
$(".infoboardWrap").remove()
$("#postsFourAcross").remove()
$("#recentRelated").remove()
$("#postComments").remove()
$(".bidwar").remove()
$(".tagsWrap").remove()
$("#tlWrap").remove()
$("footer").remove()
$(".ad").remove()

